# Generated by Django 5.1.2 on 2024-10-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_est', models.IntegerField()),
                ('date_criation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
